name: proyecto_santi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  dio: ^5.8.0+1
  http: ^1.2.2
  http_parser: ^4.0.2
  table_calendar: ^3.1.3
  window_manager: ^0.4.3
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.10.0
  font_awesome_flutter: ^10.1.0
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  firebase_storage: ^12.3.9
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.8
  firebase_database: ^11.2.1
  flutter_local_notifications: ^18.0.1
  retrofit: ^4.4.2
  flutter_map: ^5.0.0 # actualizando me da errores, no reconoce metodos, NO ACTUALIZAR
  latlong2: ^0.9.0
  geocoding: ^3.0.0
  flutter_calendar_carousel: ^2.4.4
  flutter_screenutil: ^5.0.0+2
  intl: 0.20.2
  fl_chart: ^0.69.0
  syncfusion_flutter_calendar: ^28.1.38
  syncfusion_flutter_pdfviewer: ^28.1.38
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  video_player: ^2.9.2
  chewie: ^1.8.5
  audioplayers: ^6.1.0
  record: ^6.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  emoji_picker_flutter: ^3.1.0
  flutter_linkify: ^6.0.0
  timeago: ^3.7.0
  visibility_detector: ^0.4.0+2
  uuid: ^4.5.1
  mime: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logorecortado.png
    - assets/microsoft.png