name: proyecto_santi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  dio: ^5.8.0+1
  table_calendar: ^3.0.0
  window_manager: ^0.4.3
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.10.0
  font_awesome_flutter: ^10.1.0
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1
  retrofit: ^4.4.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_calendar_carousel: ^2.0.0
  # flutter_web_plugins: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logorecortado.png
    - assets/microsoft.png